service: zelenka-serverless
app: zelenka
org: marizamj

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

  profile: serverless
  region: eu-central-1

  environment:
    SES_DESTINATION_ADDRESS: ${param:SES_DESTINATION_ADDRESS}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "arn:aws:ses:${self:provider.region}:*:*"

functions:
  emailSender:
    handler: build/handler.emailSender

    events:
      - http:
          path: /form
          method: post
          cors:
            origins:
              - http://localhost:3000
              - http://zelenka.online
